bg-de-zoomcamp:
  target: dev
  outputs:
    dev:
      type: bigquery
      method:   "{{ env_var('DBT_BIGQUERY_AUTH_METHOD', 'oauth') }}"
      project:  "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset:  "{{ env_var('DBT_BIGQUERY_TARGET_DATASET') }}"
      location: "{{ env_var('DBT_BIGQUERY_DATASET_LOCATION', 'us-central1') }}"
      priority: interactive
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1

    prod:
      type: bigquery
      method:   "{{ env_var('DBT_BIGQUERY_AUTH_METHOD', 'service-account') }}"
      project:  "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset:  "{{ env_var('DBT_BIGQUERY_TARGET_DATASET') }}"
      location: "{{ env_var('DBT_BIGQUERY_DATASET_LOCATION', 'us-central1') }}"
      keyfile:  "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      priority: interactive
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1

dbt_postgres_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host:   "{{ env_var('DBT_POSTGRES_HOST', 'localhost') }}"
      port:   "{{ env_var('DBT_POSTGRES_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
      schema: "{{ env_var('DBT_POSTGRES_TARGET_SCHEMA') }}"
      user:   "{{ env_var('DBT_POSTGRES_USER') }}"
      pass:   "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      threads: 4

    prod:
      type: postgres
      host:   "{{ env_var('DBT_POSTGRES_HOST') }}"
      port:   "{{ env_var('DBT_POSTGRES_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
      schema: "{{ env_var('DBT_POSTGRES_TARGET_SCHEMA') }}"
      user:   "{{ env_var('DBT_POSTGRES_USER') }}"
      pass:   "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      threads: 4

dbt_redshift_analytics:
  target: dev
  outputs:
    dev:
      type: redshift
      method: iam
      host:     "{{ env_var('DBT_REDSHIFT_HOST') }}"
      port:     "{{ env_var('DBT_REDSHIFT_PORT', 5439) | as_number }}"
      dbname:   "{{ env_var('DBT_REDSHIFT_DATABASE') }}"
      schema:   "{{ env_var('DBT_REDSHIFT_TARGET_SCHEMA') }}"
      user:     "{{ env_var('DBT_REDSHIFT_USER', 'admin') }}"
      password: "{{ env_var('DBT_REDSHIFT_PASSWORD') }}"
      threads: 4

    prod:
      type: redshift
      method: iam
      host:     "{{ env_var('DBT_REDSHIFT_HOST') }}"
      port:     "{{ env_var('DBT_REDSHIFT_PORT', 5439) | as_number }}"
      dbname:   "{{ env_var('DBT_REDSHIFT_DATABASE') }}"
      schema:   "{{ env_var('DBT_REDSHIFT_TARGET_SCHEMA') }}"
      user:     "{{ env_var('DBT_REDSHIFT_USER', 'admin') }}"
      password: "{{ env_var('DBT_REDSHIFT_PASSWORD') }}"
      threads: 4