sources:
  - name: ny_taxi
    database: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
    schema:   "{{ env_var('DBT_BIGQUERY_TARGET_DATASET') }}"
    tables:
      - name: yellow_cab_data
      - name: green_cab_data