
services:
  spark:
    image: docker.io/bitnami/spark:3.5
    container_name: "spark-master"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    volumes:
      - spark-logs:/master/tmp/spark-events
    networks:
      - spark-network

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    container_name: "spark-worker"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - spark-logs:/worker/tmp/spark-events
    networks:
      - spark-network

  spark-history-server:
    image: rangareddy1988/spark-history-server:${VERSION:-latest}
    container_name: spark-history-server
    environment:
      - SPARK_HISTORY_UI_PORT=18080
      - SPARK_DAEMON_MEMORY=4g
      - SPARK_HISTORY_RETAINEDAPPLICATIONS=200
      - SPARK_HISTORY_UI_MAXAPPLICATIONS=500
    ports:
     - 18080:18080
     - 4040:4040
    volumes:
     - spark-logs:/history/tmp/spark-events 
     - spark-logs:/var/log/spark
    networks:
    - spark-network

networks:
  spark-network:
    name: spark-network

volumes:
  spark-logs:
    name: spark-logs