services:
  pgdatabase:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
    ports:
      - "5444:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=blackitalian@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./volumes/pgadmin:/var/lib/pgadmin/sessions"
    ports:
      - "8080:80"
    networks:
      - pg-network

networks:
  pg-network:
    name: pg-network

