services:
  pgdatabase:
    image: postgres:13
    container_name: dez-postgres
    host_name: dez-postgres
    env_file:
      - postgres.env
    environment:
      - POSTGRES_DB=ny_taxi
    volumes:
      - "(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
    ports:
      - "8080:80"