services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - "pg-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: on-failure:5
    ports:
      - "8978:8978"
    volumes: 
      - "cloudbeaver:/opt/cloudbeaver/workspace"
    networks:
      - pg-network

  magic:
    image: mageai/mageai:latest
    container_name: mageai
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: mage:/home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 6789:6789
    volumes:
      - mage:/home/src/
      - mage:/Documents/secrets/personal-gcp.json:/home/src/personal-gcp.json
    networks:
      - pg-network
    restart: on-failure:5

networks:
  pg-network:
    name: pg-network

volumes:
  pg-data: 
    name: ingest_pgdata
  cloudbeaver:
    name: cloudbeaver
  mage:
    name: mage


